[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Authentication", "Cost/Freemium", "Trigger"]
org = "ballerinax"
name = "trigger.identityserver"
repository = "https://github.com/ballerina-platform/asyncapi-triggers"
version = "0.9.0"
distribution = "2201.12.0"
icon = "docs/icon.png"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
