name: CI

on: [push, pull_request]

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: ballerina/ballerina:2201.0.1
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - name: Build with Gradle
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
          GRADLE_USER_HOME: ~/.gradle
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew build -Prelease=false
