name: CI

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: ballerina/ballerina:swan-lake-beta6
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - name: Build with Gradle
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
          GRADLE_USER_HOME: ~/.gradle
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GIT_PAT }}
        run: |
          ./gradlew build -Prelease=false
